import { X, Database, Sparkles, HeartPulse } from 'lucide-react';
import type { Reminder } from './Reminders';

interface ReminderModalProps {
  reminder: Reminder;
  onClose: () => void;
}

export function ReminderModal({ reminder, onClose }: ReminderModalProps) {
  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center p-4 z-50" onClick={onClose}>
      <div className="bg-white rounded-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto shadow-2xl" onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div className="sticky top-0 bg-white border-b border-gray-200 px-6 py-4 flex items-start justify-between">
          <div className="flex-1 pr-4">
            <h2 className="font-semibold text-gray-900">{reminder.title}</h2>
            <p className="text-sm text-gray-500 mt-1">Scheduled for {reminder.triggerTime}</p>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
            aria-label="Close modal"
          >
            <X className="w-5 h-5 text-gray-500" />
          </button>
        </div>

        {/* Content */}
        <div className="px-6 py-6 space-y-6">
          {/* Description */}
          <div>
            <h3 className="font-medium text-gray-900 mb-2">Details</h3>
            <p className="text-gray-700 leading-relaxed mb-4">{reminder.description}</p>
            
            {/* AI and Health Disclosures */}
            <div className="space-y-3">
              {reminder.isAiGenerated && (
                <div className="flex gap-3 p-3 rounded-lg bg-indigo-50 border border-indigo-100">
                  <Sparkles className="w-5 h-5 text-indigo-600 flex-shrink-0 mt-0.5" />
                  <div className="text-sm text-indigo-900">
                    <span className="font-medium block mb-0.5">AI-Generated Content</span>
                    This recommendation was generated by artificial intelligence based on your activity patterns. Please exercise causion and verify the result yourself.
                  </div>
                </div>
              )}

              {reminder.isHealthRelated && (
                <div className="flex gap-3 p-3 rounded-lg bg-amber-50 border border-amber-100">
                  <HeartPulse className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
                  <div className="text-sm text-amber-900">
                    <span className="font-medium block mb-0.5">Health Notice</span>
                    This suggestion relates to your physical wellbeing. Please verify it manually to ensure it fits your current environment and physical needs.
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Data Sources */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <Database className="w-5 h-5 text-blue-600" />
              <h3 className="font-medium text-gray-900">Data Used to Generate This Recommendation</h3>
            </div>
            <div className="bg-blue-50 border border-blue-100 rounded-xl p-4">
              <ul className="space-y-3">
                {reminder.dataUsed.map((data, index) => (
                  <li key={index} className="flex items-start gap-3">
                    <div className="w-1.5 h-1.5 rounded-full bg-blue-600 mt-2 flex-shrink-0" />
                    <span className="text-sm text-gray-700">{data}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex gap-3 pt-2">
            <button className="flex-1 px-4 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
              Mark as Done
            </button>
            <button className="px-4 py-3 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors">
              Snooze
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}